@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 3




class Coordinator{

}

class VaccinationCenter {
    -name
    -address
    -phoneNumber
    -emailAddress
    -faxNumber
    -websiteAddress
    -openingHours
    -closingHours
    -slotDuration
    -maxNumVaxPerSlot

}


class Nurse {


}

class Receptionist{

}

class Administrator{

}

class Schedule{
}

class SNSUser {

}

class VaccineType{
    -disease
    -type
    -minAge
    -maxAge
    -dosePerAgeGroup
    -dosageML
    -timeInterval
}

class Vaccine{
    -lotNum
}


class VaccinationProcess{



}

Nurse "*" -- "1" VaccinationProcess: updates >


Receptionist "1" -- "1" VaccinationCenter: updates >
Receptionist "*" -- "1" VaccinationProcess: updates >


VaccinationCenter "1" -- "0..*" SNSUser: has >
VaccinationCenter "1" -- "1" Coordinator: has >

Coordinator "1" -- "1" VaccinationProcess: monitors >

Nurse "1" -- "*" Schedule: creates >
Nurse "1" -- "*" SNSUser: updates >

Schedule "1" -- "1" VaccinationCenter: has >

SNSUser "1" -- "*" Schedule: creates >
SNSUser "1" - "0..*" Vaccine: gets >

Administrator "1" -- "*" VaccinationCenter: manages >
Administrator "1" -- "*" Nurse: manages >
Administrator "1" -- "*" Receptionist: manages >
Administrator "1" -- "*" SNSUser: manages >
Administrator "1" -- "*" Coordinator: manages >

Vaccine "1" -- "1" VaccineType: has >
@enduml